/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 logomodel.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/logomodel.gltf')
  return (
    <group scale={0.4} {...props} dispose={null}>
      <mesh geometry={nodes.Ресурс_4.geometry} material={materials['Plastic Shader']} position={[0, 0.844, 0.422]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ресурс_5.geometry} material={materials['Sweet Plastic']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/logomodel.gltf')
