/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 metalmodel.gltf 
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/badoo-logo-2047ec6cf0304ac6bc67e4801946222f
Title: Badoo Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Metalmodel(props) {
  const { nodes, materials } = useGLTF('/metalmodel.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.blank} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.logo} />
      </group>
    </group>
  )
}

useGLTF.preload('/metalmodel.gltf')
